name: StreamAutomaticReleaseTest

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"

scripts:
  lint:pub:
    run: melos exec -c 1 --no-published --no-private --order-dependents -- "flutter pub publish -n"
    description: Dry run `pub publish` in all packages.

  release:pub:
    run: melos exec -c 1 --no-published --no-private --order-dependents -- "flutter pub publish -f"
    description: Publish all packages to pub.dev.