name: stream_automatic_release_package_two
description: A test package for automatic release check using Melos.
repository: https://github.com/xsahil03x/stream-automatic-release-test
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
